# Generated by Django 6.0.6 on 2026-06-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('not_confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Order Status History',
            },
        ),
    ]
