# Generated by Django 6.0.3 on 2026-04-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
