# Generated by Django 6.0.3 on 2026-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='order_final_status',
            field=models.CharField(choices=[('not_confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed'), ('being_prepared', 'Being Prepared'), ('food_pickup', 'Food Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_confirmed', max_length=20),
        ),
    ]
