# Generated by Django 6.0.3 on 2026-05-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_user_age_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodtracking',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_wishlist',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodTracking',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='food',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
